<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260209160815 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE categories (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid UUID NOT NULL, name VARCHAR(150) NOT NULL, description TEXT DEFAULT NULL, icon VARCHAR(50) DEFAULT NULL, sort_order SMALLINT NOT NULL, is_active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, deleted_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, restaurant_id INT DEFAULT NULL, image_media_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_3AF34668D17F50A6 ON categories (uuid)');
        $this->addSql('CREATE INDEX IDX_3AF34668656F53DD ON categories (image_media_id)');
        $this->addSql('CREATE INDEX idx_categories_restaurant ON categories (restaurant_id)');
        $this->addSql('CREATE UNIQUE INDEX uq_category_name_per_restaurant ON categories (restaurant_id, name)');
        $this->addSql('CREATE TABLE locales (id SMALLINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(5) NOT NULL, name VARCHAR(50) NOT NULL, is_active BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_E59B54BB77153098 ON locales (code)');
        $this->addSql('CREATE TABLE media (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid UUID NOT NULL, original_filename VARCHAR(255) NOT NULL, storage_path VARCHAR(500) NOT NULL, mime_type VARCHAR(50) NOT NULL, file_size INT NOT NULL, width SMALLINT DEFAULT NULL, height SMALLINT DEFAULT NULL, alt_text VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, deleted_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, restaurant_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_6A2CA10CD17F50A6 ON media (uuid)');
        $this->addSql('CREATE INDEX idx_media_restaurant ON media (restaurant_id)');
        $this->addSql('CREATE TABLE pdf_templates (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, slug VARCHAR(50) NOT NULL, name VARCHAR(100) NOT NULL, description VARCHAR(500) DEFAULT NULL, preview_image_url VARCHAR(500) DEFAULT NULL, template_path VARCHAR(255) NOT NULL, page_size VARCHAR(10) NOT NULL, labels_per_page SMALLINT NOT NULL, placeholders JSON NOT NULL, is_active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_E78B85EF989D9B62 ON pdf_templates (slug)');
        $this->addSql('CREATE TABLE product_approval_log (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, action VARCHAR(20) NOT NULL, note TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, product_id INT NOT NULL, performed_by_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_69B147CD4584665A ON product_approval_log (product_id)');
        $this->addSql('CREATE INDEX IDX_69B147CD2E65C292 ON product_approval_log (performed_by_id)');
        $this->addSql('CREATE INDEX idx_approval_log_product ON product_approval_log (product_id, created_at)');
        $this->addSql('CREATE TABLE product_images (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, sort_order SMALLINT NOT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, product_id INT NOT NULL, media_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8263FFCE4584665A ON product_images (product_id)');
        $this->addSql('CREATE INDEX IDX_8263FFCEEA9FDD75 ON product_images (media_id)');
        $this->addSql('CREATE INDEX idx_product_images_sorted ON product_images (product_id, sort_order)');
        $this->addSql('CREATE UNIQUE INDEX uq_product_media ON product_images (product_id, media_id)');
        $this->addSql('CREATE TABLE products (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid UUID NOT NULL, name VARCHAR(200) NOT NULL, description TEXT DEFAULT NULL, price NUMERIC(10, 2) NOT NULL, status VARCHAR(20) NOT NULL, submitted_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, is_featured BOOLEAN NOT NULL, allergens JSON DEFAULT NULL, sort_order SMALLINT NOT NULL, is_active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, deleted_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, restaurant_id INT DEFAULT NULL, category_id INT NOT NULL, catalog_product_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_B3BA5A5AD17F50A6 ON products (uuid)');
        $this->addSql('CREATE INDEX IDX_B3BA5A5A12469DE2 ON products (category_id)');
        $this->addSql('CREATE INDEX IDX_B3BA5A5AF0AE9481 ON products (catalog_product_id)');
        $this->addSql('CREATE INDEX idx_products_restaurant ON products (restaurant_id)');
        $this->addSql('CREATE INDEX idx_products_category_sorted ON products (restaurant_id, category_id, sort_order)');
        $this->addSql('CREATE INDEX idx_products_pending ON products (status, submitted_at)');
        $this->addSql('CREATE TABLE qr_codes (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid UUID NOT NULL, type VARCHAR(20) NOT NULL, table_number SMALLINT DEFAULT NULL, table_label VARCHAR(50) DEFAULT NULL, encoded_url VARCHAR(500) NOT NULL, storage_path VARCHAR(500) DEFAULT NULL, is_active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, restaurant_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A0780317D17F50A6 ON qr_codes (uuid)');
        $this->addSql('CREATE INDEX idx_qr_codes_restaurant ON qr_codes (restaurant_id)');
        $this->addSql('CREATE TABLE restaurant_pages (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(20) NOT NULL, title VARCHAR(200) NOT NULL, body TEXT DEFAULT NULL, is_published BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, restaurant_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_pages_restaurant ON restaurant_pages (restaurant_id)');
        $this->addSql('CREATE UNIQUE INDEX uq_restaurant_page_type ON restaurant_pages (restaurant_id, type)');
        $this->addSql('CREATE TABLE restaurant_social_links (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, platform VARCHAR(30) NOT NULL, url VARCHAR(500) NOT NULL, sort_order SMALLINT NOT NULL, restaurant_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_social_links_restaurant ON restaurant_social_links (restaurant_id)');
        $this->addSql('CREATE UNIQUE INDEX uq_restaurant_platform ON restaurant_social_links (restaurant_id, platform)');
        $this->addSql('CREATE TABLE restaurants (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid UUID NOT NULL, name VARCHAR(150) NOT NULL, slug VARCHAR(100) NOT NULL, description TEXT DEFAULT NULL, phone VARCHAR(30) DEFAULT NULL, email VARCHAR(180) DEFAULT NULL, address TEXT DEFAULT NULL, city VARCHAR(100) DEFAULT NULL, country_code VARCHAR(2) DEFAULT NULL, latitude NUMERIC(10, 7) DEFAULT NULL, longitude NUMERIC(10, 7) DEFAULT NULL, default_locale VARCHAR(5) NOT NULL, currency_code VARCHAR(3) NOT NULL, color_overrides JSON DEFAULT NULL, custom_css TEXT DEFAULT NULL, meta_title VARCHAR(160) DEFAULT NULL, meta_description VARCHAR(320) DEFAULT NULL, is_active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, deleted_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, logo_media_id INT DEFAULT NULL, cover_media_id INT DEFAULT NULL, theme_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_AD837724D17F50A6 ON restaurants (uuid)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_AD837724989D9B62 ON restaurants (slug)');
        $this->addSql('CREATE INDEX IDX_AD837724BAAE86A3 ON restaurants (logo_media_id)');
        $this->addSql('CREATE INDEX IDX_AD837724329A1B2E ON restaurants (cover_media_id)');
        $this->addSql('CREATE INDEX IDX_AD83772459027487 ON restaurants (theme_id)');
        $this->addSql('CREATE TABLE roles (id SMALLINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(50) NOT NULL, description VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_B63E2EC75E237E06 ON roles (name)');
        $this->addSql('CREATE TABLE themes (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, slug VARCHAR(50) NOT NULL, name VARCHAR(100) NOT NULL, description VARCHAR(500) DEFAULT NULL, preview_image_url VARCHAR(500) DEFAULT NULL, default_config JSON NOT NULL, is_active BOOLEAN NOT NULL, sort_order SMALLINT NOT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_154232DE989D9B62 ON themes (slug)');
        $this->addSql('CREATE TABLE translations (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, entity_type VARCHAR(50) NOT NULL, entity_id INT NOT NULL, locale VARCHAR(5) NOT NULL, field VARCHAR(50) NOT NULL, value TEXT NOT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_translations_lookup ON translations (entity_type, entity_id, locale)');
        $this->addSql('CREATE UNIQUE INDEX uq_translation_entity_locale_field ON translations (entity_type, entity_id, locale, field)');
        $this->addSql('CREATE TABLE users (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid UUID NOT NULL, email VARCHAR(180) NOT NULL, password_hash VARCHAR(255) NOT NULL, first_name VARCHAR(100) NOT NULL, last_name VARCHAR(100) NOT NULL, is_active BOOLEAN NOT NULL, last_login_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, deleted_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, restaurant_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1483A5E9D17F50A6 ON users (uuid)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1483A5E9E7927C74 ON users (email)');
        $this->addSql('CREATE INDEX idx_users_restaurant ON users (restaurant_id)');
        $this->addSql('CREATE TABLE user_roles (user_id INT NOT NULL, role_id SMALLINT NOT NULL, PRIMARY KEY (user_id, role_id))');
        $this->addSql('CREATE INDEX IDX_54FCD59FA76ED395 ON user_roles (user_id)');
        $this->addSql('CREATE INDEX IDX_54FCD59FD60322AC ON user_roles (role_id)');
        $this->addSql('ALTER TABLE categories ADD CONSTRAINT FK_3AF34668B1E7706E FOREIGN KEY (restaurant_id) REFERENCES restaurants (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE categories ADD CONSTRAINT FK_3AF34668656F53DD FOREIGN KEY (image_media_id) REFERENCES media (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE media ADD CONSTRAINT FK_6A2CA10CB1E7706E FOREIGN KEY (restaurant_id) REFERENCES restaurants (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE product_approval_log ADD CONSTRAINT FK_69B147CD4584665A FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE product_approval_log ADD CONSTRAINT FK_69B147CD2E65C292 FOREIGN KEY (performed_by_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE product_images ADD CONSTRAINT FK_8263FFCE4584665A FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE product_images ADD CONSTRAINT FK_8263FFCEEA9FDD75 FOREIGN KEY (media_id) REFERENCES media (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE products ADD CONSTRAINT FK_B3BA5A5AB1E7706E FOREIGN KEY (restaurant_id) REFERENCES restaurants (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE products ADD CONSTRAINT FK_B3BA5A5A12469DE2 FOREIGN KEY (category_id) REFERENCES categories (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE products ADD CONSTRAINT FK_B3BA5A5AF0AE9481 FOREIGN KEY (catalog_product_id) REFERENCES products (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE qr_codes ADD CONSTRAINT FK_A0780317B1E7706E FOREIGN KEY (restaurant_id) REFERENCES restaurants (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE restaurant_pages ADD CONSTRAINT FK_6A6956A4B1E7706E FOREIGN KEY (restaurant_id) REFERENCES restaurants (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE restaurant_social_links ADD CONSTRAINT FK_662197CAB1E7706E FOREIGN KEY (restaurant_id) REFERENCES restaurants (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE restaurants ADD CONSTRAINT FK_AD837724BAAE86A3 FOREIGN KEY (logo_media_id) REFERENCES media (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE restaurants ADD CONSTRAINT FK_AD837724329A1B2E FOREIGN KEY (cover_media_id) REFERENCES media (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE restaurants ADD CONSTRAINT FK_AD83772459027487 FOREIGN KEY (theme_id) REFERENCES themes (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE users ADD CONSTRAINT FK_1483A5E9B1E7706E FOREIGN KEY (restaurant_id) REFERENCES restaurants (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_roles ADD CONSTRAINT FK_54FCD59FA76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_roles ADD CONSTRAINT FK_54FCD59FD60322AC FOREIGN KEY (role_id) REFERENCES roles (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE categories DROP CONSTRAINT FK_3AF34668B1E7706E');
        $this->addSql('ALTER TABLE categories DROP CONSTRAINT FK_3AF34668656F53DD');
        $this->addSql('ALTER TABLE media DROP CONSTRAINT FK_6A2CA10CB1E7706E');
        $this->addSql('ALTER TABLE product_approval_log DROP CONSTRAINT FK_69B147CD4584665A');
        $this->addSql('ALTER TABLE product_approval_log DROP CONSTRAINT FK_69B147CD2E65C292');
        $this->addSql('ALTER TABLE product_images DROP CONSTRAINT FK_8263FFCE4584665A');
        $this->addSql('ALTER TABLE product_images DROP CONSTRAINT FK_8263FFCEEA9FDD75');
        $this->addSql('ALTER TABLE products DROP CONSTRAINT FK_B3BA5A5AB1E7706E');
        $this->addSql('ALTER TABLE products DROP CONSTRAINT FK_B3BA5A5A12469DE2');
        $this->addSql('ALTER TABLE products DROP CONSTRAINT FK_B3BA5A5AF0AE9481');
        $this->addSql('ALTER TABLE qr_codes DROP CONSTRAINT FK_A0780317B1E7706E');
        $this->addSql('ALTER TABLE restaurant_pages DROP CONSTRAINT FK_6A6956A4B1E7706E');
        $this->addSql('ALTER TABLE restaurant_social_links DROP CONSTRAINT FK_662197CAB1E7706E');
        $this->addSql('ALTER TABLE restaurants DROP CONSTRAINT FK_AD837724BAAE86A3');
        $this->addSql('ALTER TABLE restaurants DROP CONSTRAINT FK_AD837724329A1B2E');
        $this->addSql('ALTER TABLE restaurants DROP CONSTRAINT FK_AD83772459027487');
        $this->addSql('ALTER TABLE users DROP CONSTRAINT FK_1483A5E9B1E7706E');
        $this->addSql('ALTER TABLE user_roles DROP CONSTRAINT FK_54FCD59FA76ED395');
        $this->addSql('ALTER TABLE user_roles DROP CONSTRAINT FK_54FCD59FD60322AC');
        $this->addSql('DROP TABLE categories');
        $this->addSql('DROP TABLE locales');
        $this->addSql('DROP TABLE media');
        $this->addSql('DROP TABLE pdf_templates');
        $this->addSql('DROP TABLE product_approval_log');
        $this->addSql('DROP TABLE product_images');
        $this->addSql('DROP TABLE products');
        $this->addSql('DROP TABLE qr_codes');
        $this->addSql('DROP TABLE restaurant_pages');
        $this->addSql('DROP TABLE restaurant_social_links');
        $this->addSql('DROP TABLE restaurants');
        $this->addSql('DROP TABLE roles');
        $this->addSql('DROP TABLE themes');
        $this->addSql('DROP TABLE translations');
        $this->addSql('DROP TABLE users');
        $this->addSql('DROP TABLE user_roles');
    }
}
