<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260211170000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add site settings and widgets for public CMS';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE site_settings (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, key_name VARCHAR(120) NOT NULL, value TEXT NOT NULL, updated_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_site_settings_key ON site_settings (key_name)');

        $this->addSql('CREATE TABLE site_widgets (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, key_name VARCHAR(120) NOT NULL, type VARCHAR(40) NOT NULL, config JSON NOT NULL, sort_order SMALLINT NOT NULL, is_active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_site_widgets_key ON site_widgets (key_name)');
        $this->addSql('CREATE INDEX idx_site_widgets_active_order ON site_widgets (is_active, sort_order)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE site_widgets');
        $this->addSql('DROP TABLE site_settings');
    }
}
