<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260211113000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add plan, customer-account, subscription, blog and multi-restaurant user support';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE plans (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(50) NOT NULL, name VARCHAR(120) NOT NULL, description TEXT DEFAULT NULL, max_restaurants INT NOT NULL, max_users INT NOT NULL, yearly_price NUMERIC(10, 2) NOT NULL, is_active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_98B1D4B377153098 ON plans (code)');

        $this->addSql('CREATE TABLE customer_accounts (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid UUID NOT NULL, name VARCHAR(160) NOT NULL, email VARCHAR(180) DEFAULT NULL, is_active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_AA8896E4D17F50A6 ON customer_accounts (uuid)');

        $this->addSql('CREATE TABLE customer_subscriptions (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, customer_account_id INT NOT NULL, plan_id INT NOT NULL, starts_at DATE NOT NULL, ends_at DATE NOT NULL, is_active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_57D5558A6E8CFE8A ON customer_subscriptions (customer_account_id)');
        $this->addSql('CREATE INDEX IDX_57D5558A472B7833 ON customer_subscriptions (plan_id)');

        $this->addSql('CREATE TABLE blog_posts (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid UUID NOT NULL, title VARCHAR(180) NOT NULL, slug VARCHAR(200) NOT NULL, body TEXT NOT NULL, meta_title VARCHAR(160) DEFAULT NULL, meta_description VARCHAR(320) DEFAULT NULL, is_published BOOLEAN NOT NULL, published_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_BA40EC03D17F50A6 ON blog_posts (uuid)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_BA40EC03989D9B62 ON blog_posts (slug)');
        $this->addSql('CREATE INDEX idx_blog_posts_published ON blog_posts (is_published, published_at)');

        $this->addSql('CREATE TABLE site_contents (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, key_name VARCHAR(80) NOT NULL, title VARCHAR(200) NOT NULL, body TEXT NOT NULL, is_published BOOLEAN NOT NULL, updated_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_7471F7CC1A53199B ON site_contents (key_name)');

        $this->addSql('CREATE TABLE user_restaurants (user_id INT NOT NULL, restaurant_id INT NOT NULL, PRIMARY KEY(user_id, restaurant_id))');
        $this->addSql('CREATE INDEX IDX_5736A4B8A76ED395 ON user_restaurants (user_id)');
        $this->addSql('CREATE INDEX IDX_5736A4B8B1E7706E ON user_restaurants (restaurant_id)');

        $this->addSql('ALTER TABLE users ADD customer_account_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE restaurants ADD customer_account_id INT DEFAULT NULL');
        $this->addSql('CREATE INDEX idx_users_customer_account ON users (customer_account_id)');
        $this->addSql('CREATE INDEX idx_restaurants_customer_account ON restaurants (customer_account_id)');

        $this->addSql('ALTER TABLE customer_subscriptions ADD CONSTRAINT FK_57D5558A6E8CFE8A FOREIGN KEY (customer_account_id) REFERENCES customer_accounts (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE customer_subscriptions ADD CONSTRAINT FK_57D5558A472B7833 FOREIGN KEY (plan_id) REFERENCES plans (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_restaurants ADD CONSTRAINT FK_5736A4B8A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_restaurants ADD CONSTRAINT FK_5736A4B8B1E7706E FOREIGN KEY (restaurant_id) REFERENCES restaurants (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE users ADD CONSTRAINT FK_1483A5E96E8CFE8A FOREIGN KEY (customer_account_id) REFERENCES customer_accounts (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE restaurants ADD CONSTRAINT FK_AD8377246E8CFE8A FOREIGN KEY (customer_account_id) REFERENCES customer_accounts (id) ON DELETE SET NULL NOT DEFERRABLE');

        $this->addSql('INSERT INTO user_restaurants (user_id, restaurant_id) SELECT id, restaurant_id FROM users WHERE restaurant_id IS NOT NULL ON CONFLICT DO NOTHING');

        $this->addSql("INSERT INTO plans (code, name, description, max_restaurants, max_users, yearly_price, is_active, created_at, updated_at) VALUES ('free', 'Free', '1 restoran 1 kullanici yillik plan', 1, 1, 0.00, true, NOW(), NOW())");
        $this->addSql("INSERT INTO plans (code, name, description, max_restaurants, max_users, yearly_price, is_active, created_at, updated_at) VALUES ('premium', 'Premium', '20 restoran 25 kullanici yillik plan', 20, 25, 0.00, true, NOW(), NOW())");
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE customer_subscriptions DROP CONSTRAINT FK_57D5558A6E8CFE8A');
        $this->addSql('ALTER TABLE customer_subscriptions DROP CONSTRAINT FK_57D5558A472B7833');
        $this->addSql('ALTER TABLE user_restaurants DROP CONSTRAINT FK_5736A4B8A76ED395');
        $this->addSql('ALTER TABLE user_restaurants DROP CONSTRAINT FK_5736A4B8B1E7706E');
        $this->addSql('ALTER TABLE users DROP CONSTRAINT FK_1483A5E96E8CFE8A');
        $this->addSql('ALTER TABLE restaurants DROP CONSTRAINT FK_AD8377246E8CFE8A');

        $this->addSql('DROP TABLE customer_subscriptions');
        $this->addSql('DROP TABLE blog_posts');
        $this->addSql('DROP TABLE site_contents');
        $this->addSql('DROP TABLE user_restaurants');

        $this->addSql('DROP INDEX idx_users_customer_account');
        $this->addSql('DROP INDEX idx_restaurants_customer_account');
        $this->addSql('ALTER TABLE users DROP customer_account_id');
        $this->addSql('ALTER TABLE restaurants DROP customer_account_id');

        $this->addSql('DROP TABLE customer_accounts');
        $this->addSql('DROP TABLE plans');
    }
}
