<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260211143000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add blog view counter and blog comments';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('ALTER TABLE blog_posts ADD view_count INT DEFAULT 0 NOT NULL');

        $this->addSql('CREATE TABLE blog_comments (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, post_id INT NOT NULL, author_name VARCHAR(120) NOT NULL, body TEXT NOT NULL, is_published BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_7A89CE824B89032C ON blog_comments (post_id)');
        $this->addSql('CREATE INDEX idx_blog_comments_post_published ON blog_comments (post_id, is_published, created_at)');
        $this->addSql('ALTER TABLE blog_comments ADD CONSTRAINT FK_7A89CE824B89032C FOREIGN KEY (post_id) REFERENCES blog_posts (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE blog_comments DROP CONSTRAINT FK_7A89CE824B89032C');
        $this->addSql('DROP TABLE blog_comments');

        $this->addSql('ALTER TABLE blog_posts DROP view_count');
    }
}
